//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst_ProductList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            // using System.Collections.Generic; tanýmlamasaydýk;
            // this.Products = new System.Collections.Generic.HashSet<Product>(); þkelinde yazabilirdik. ama her kullandýðýmýz yerde bu tanýmlamyý yapmak zorunda kalýrdýk.using kullanmk bize kod yazarken kolaylýk saðlar.
            this.Products = new HashSet<Product>(); //Performans probleminden dolayý hashset kullanýldý
        }
    
        public int CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public byte[] Picture { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; } //one to many iliþki
    }
}
