//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst_ProductList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string QuantityPerUnit { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<short> UnitsInStock { get; set; }
        public Nullable<short> UnitsOnOrder { get; set; }
        public Nullable<short> ReorderLevel { get; set; }
        public bool Discontinued { get; set; }
    
        public virtual Category Category { get; set; } //one to one ilþiki bknz: category.cs
                                                       //bu yapýyý joinlemeden Category içinden tüm o classýn içindeki alanlara ulaþmak için yazýlýr.
        //virtual tanýmlamadýðýmýzda bu sýnýfý tanýmladýðýmýzda hafýza da boþyere en baþýndan burasýyla alakalý bütün bilgileri alýr.Bu daha hafýzayý yorar.Buna lazy Loading denir. yazarsak ise eager loading denir.
        //virtual yazmazsak hatalar alabiliriz o yüzden virtual yazmamýz gerekir.

        
    }
}
